<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUYYklGr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUYYklGr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUYYklGr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUYYklGr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUYYklGr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UYYklGr',
    'container.build_id' => '80227cf0',
    'container.build_time' => 1570456262,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUYYklGr');
